language: node_js
node_js:
  - "9"
script:
  - npm run lint
  - npm test
  - npm run build
deploy:
  provider: npm
  email: geminiyellow@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: production
    skip_cleanup: true
